src/objects/Budget_Line__c.object
<CustomObject>
    <description>Level 3 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Annual_Budget__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if your budget is associated to an Annual PR</inlineHelpText>
        <label>Annual Budget?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Line_Amount__c</fullName>
        <label>Budget Line Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Quarters__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Number of quarters this recurring budget will be repeated</inlineHelpText>
        <label># of Quarters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>Program_Budget__r.Budget_Owner__r.Period__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Budget_Amount__c</fullName>
        <formula>Program_Budget__r.Program_Budget_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Budget__c</fullName>
        <label>Program Budget</label>
        <referenceTo>Program_Budget__c</referenceTo>
        <relationshipLabel>Budget Lines (Level 3)</relationshipLabel>
        <relationshipName>Budget_Lines1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recurring_Start_Period__c</fullName>
        <label>Recurring_Start_Period</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budget Lines</relationshipLabel>
        <relationshipName>Budget_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a One-Time Budget Request, or recurring request?</inlineHelpText>
        <label>Recurring?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AMER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LACA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Budget Line</label>
    <nameField>
        <label>Budget Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budgets__c.object
<CustomObject>
    <description>Level 1 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Area__c</fullName>
        <label>Budget Area</label>
        <picklist>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Projects</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget_Owner__c</fullName>
        <label>Budget Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Spend Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTINGENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Spend Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollup_of_Program_Budget_Amount__c</fullName>
        <label>Allocated Program Budget Amount</label>
        <summarizedField>Program_Budget__c.Program_Budget_Amount__c</summarizedField>
        <summaryForeignKey>Program_Budget__c.Budget_Owner__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Period__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>this number must be the  numeric year (2011, 2012, etc) or the numeric portion of the quarter (1,2,3,4 = Q1,Q2,Q3,Q4)</description>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentPeriod__c</fullName>
        <label>ParentPeriod</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Periods (ParentPeriod)</relationshipLabel>
        <relationshipName>Periods2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Budget__c.object
<CustomObject>
    <description>Level 2 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Area__c</fullName>
        <label>Budget Area</label>
        <picklist>
            <picklistValues>
                <fullName>Generica Area 1 (Update)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generica Area 2 (Update)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generica Area 3 (Update)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget_Owner__c</fullName>
        <label>Parent Budget</label>
        <referenceTo>Budgets__c</referenceTo>
        <relationshipLabel>Program Budgets (Level 2)</relationshipLabel>
        <relationshipName>Program_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Budget_Amount__c</fullName>
        <label>Program Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <controllingField>Budget_Area__c</controllingField>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Books/Brochures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branding/Awareness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region DO NOT USE</label>
        <picklist>
            <picklistValues>
                <fullName>US/Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L. America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rollup_of_Budget_Lines__c</fullName>
        <label>Rollup of Budget Lines</label>
        <summarizedField>Budget_Line__c.Budget_Line_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Budget_Line__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Budget_Line__c.Program_Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <inlineHelpText>If filled in, this short name will be added to the end of the Program Budget name</inlineHelpText>
        <label>Short Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BudgetRecurringUtility.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

/* This class provides the framework for implementing Recurring budgets.
 * The basic flow is: 
 *    (a) logic to process recurring budget
 *
 * @since 2010-06
 */
public class BudgetRecurringUtility {
	
    public static String errorMsg {get;set;}
    public static Boolean isTest {get;set;} // for testing purposes
    
    static {
    	isTest = false;
    }
    
    /*
     * Method: processRecurringBudget
     * Method called by BudgetLineTrigger on AfterInsert, AfterUpdate
     * When we insert or update a Budget Line (Budget_Line__c), if Recurring is true, then It copies the tree
     * to the periods that are calculated from Recurring_Start_Period__c and Number_of_Quarters
     */
    public static void processRecurringBudget(List<Budget_Line__c> budgetLines, List<Budget_Line__c> oldBudgetLines) {
		Map<Id, Budget_Line__c> oldBudgetLinesById = new Map<Id, Budget_Line__c>();
		if (oldBudgetLines != null)
		{
			for (Budget_Line__c oldBudget : oldBudgetLines)
			{
				oldBudgetLinesById.put(oldBudget.Id, oldBudget);
			}
		}
		
		for ( Budget_Line__c budgetLine : budgetLines)
		{
			if ((budgetLine.Recurring__c == true && oldBudgetLines == null) || (budgetLine.Recurring__c == true && oldBudgetLinesById.get(budgetLine.Id).Recurring__c == false)){
				
			
	 		if(budgetLine.Recurring_Start_Period__c == null || budgetLine.Number_of_Quarters__c == null || budgetLine.Number_of_Quarters__c < 2){return;}
	 	
	 		Integer j = 1; 		
	 		BudgetNode recurringTree = new BudgetNode(j++);  
	    	BudgetPeriodUtility bpu = new BudgetPeriodUtility();
	    	Map<String, Budgets__c> bOwnersMap = new Map<String, Budgets__c>();
	    	Map<String, List<Budget_Line__c>> bLineMap = new Map<String, List<Budget_Line__c>>();
	    	List<Program_Budget__c> pbList = new List<Program_Budget__c>();
	    	
	    	
	    	Period__c recurringStartPeriod = [select Id, Name, Start_Date__c, End_Date__c, Type__c, Number__c, ParentPeriod__c, ParentPeriod__r.Id, ParentPeriod__r.Name, ParentPeriod__r.Start_Date__c, ParentPeriod__r.End_Date__c, ParentPeriod__r.Type__c, ParentPeriod__r.Number__c from Period__c where Id =: budgetLine.Recurring_Start_Period__c limit 1][0];
	  		Program_Budget__c budgetParent = [select Id, 
	  												 Name,
	  												 Short_Name__c, 
	  												 Program_Type__c, 
	  												 Region__c, 
	  												 RecordTypeId,
	  												 Budget_Area__c,
	  												 Budget_Owner__r.Id, 
	  												 Budget_Owner__r.Name, 
	  												 Budget_Owner__r.RecordTypeId,
	  												 Budget_Owner__r.Budget_Area__c,
	  												 Rollup_of_Budget_Lines__c
	  										 from Program_Budget__c where Id =: budgetLine.Program_Budget__c limit 1];   	
	    	
	    	List<Period__c> recurringPeriods = bpu.getRecurringPeriods(recurringStartPeriod,Math.round(budgetLine.Number_of_Quarters__c));
	    	
	    	// We retrieve the Budget Owners to store them in a Map
	    	for (Budgets__c bo : [select Id, Name, Budget_Amount__c, Rollup_of_Program_Budget_Amount__c, (Select Id, Name, Rollup_of_Budget_Lines__c, Program_Budget_Amount__c, Budget_Owner__c from Program_Budgets__r) from Budgets__c where Period__c in : recurringPeriods]) {
	    		if(!bOwnersMap.containsKey(bo.Name)) bOwnersMap.put(bo.Name, bo);
	    		if (bo.Program_Budgets__r.size() > 0) pbList.addAll(bo.Program_Budgets__r); 
	    	}
	    	
	    	// We retrieve the Budget Lines to store them in a Map 
			for (Budget_Line__c bl : [select Id, Name, Budget_Line_Amount__c, Program_Budget__c from Budget_Line__c where Program_Budget__c in : pbList]) {
				if (bLineMap.containsKey(bl.Program_Budget__c)) {
					bLineMap.get(bl.Program_Budget__c).add(bl);
				} else {
					bLineMap.put(bl.Program_Budget__c, new List<Budget_Line__c>{bl});
				}
			}     	
	    	// returns a list of all the periods for which we are going to copy the tree 
			// Iterate over the periods - We will check if the tree on which the new Budget Line belongs to, exists for other periods
	    	for (Period__c p : recurringPeriods) {
				// Items to copy
				Program_Budget__c bl3 = new Program_Budget__c(Short_Name__c = budgetParent.Short_Name__c, 
															  Program_Type__c = budgetParent.Program_Type__c,
															  Budget_Area__c = budgetParent.Budget_Area__c, 
															  Region__c = budgetParent.Region__c, 
															  RecordTypeId = budgetParent.RecordTypeId,
															  Program_Budget_Amount__c = 0);
	
							
				Budget_Line__c bl4 = new Budget_Line__c(Short_Name__c = budgetLine.Short_Name__c,
														Annual_Budget__c = false,
														Recurring__c = false,	 
														Region__c = budgetLine.Region__c, 
														RecordTypeId = budgetLine.RecordTypeId,
														Description__c = budgetLine.Description__c,
														Budget_Line_Amount__c = 0);
														
	    		
	    		// We generate the Name to see if it exists in the map that have all the Budget Owners
	    		// Since the Budget Owner Name generates automatically on insertion, we need to form it as it is
	    		String auxBOwnerName = budgetParent.Budget_Owner__r.Name;
				String bOwnerName = auxBOwnerName.replace(auxBOwnerName.substring(0,6), p.Name);
				// If it is in the Map, means that there is a Budget Owner with the same name but for a diferent period, 
				// so we go further and check if the Program Budget also exists.    					    		
	    		if (bOwnersMap.containsKey(bOwnerName))	{
	    			Budgets__c b = bOwnersMap.get(bOwnerName);
	    			BudgetNode BL1Node = new Budgets(j++, b);
	    			recurringTree.add(BL1Node); // add node to recurringTree
	    			BudgetNode BL3Node = null;
	    			// We iterate over the Program Budgets that are related to the Budget Owner
	    			for (Program_Budget__c pb : b.Program_Budgets__r) {
	    				BudgetNode BL4Node = null;
	   					// We generate the Program Budget Name 
	    				String auxPBudgetName = budgetParent.Name;
	    				String pBudgetName = auxPBudgetName.replace(auxPBudgetName.substring(0,6), p.Name);
	    				// Check if a Program Budget exist for this period, if it does then we don't add it as a new Program Budget
	    				if (pb.Name == pBudgetName) {
	    					BL3Node = new ProgramBudget(j++, pb);
	    					BL1Node.add(BL3Node);
	    					// Check if there are Budget Lines for current Program Budget
	    					if (bLineMap.containsKey(pb.Id)) {
	    						List<Budget_Line__c> auxBlList = bLineMap.get(pb.Id);
	    						// We iterate over the Budget Lines that are related to the Program Budget
	    						for (Budget_Line__c bl : auxBlList) {
	    							// Generate Budget Line name
	    							String auxBlName = budgetLine.Name;
	    							String blName = auxBlName.replace(auxBlName.substring(0,6), p.Name);
	    							// Check if a Budget Line exists for this period, if it does then we don't add it as a new Budget Line
	    							if (bl.Name == blName) {
			    						BL4Node = new BudgetLine(j++, bl);
	    								BL3Node.add(BL4Node);
	    								break;					
	    							}
	    						}
	    					}
	    					// If BL4Node is null means that we have to add a new budget line for the period I am iterating over
							if (BL4Node == null) {
								BL4Node = new BudgetLine(j++, bl4);
								BL3Node.add(BL4Node);
							}      										
	    				}
	    			} 
	    			// If BL3Node is null means that we have to add a new Program Budget and a Budget Line for the period I am iteration over.
	    			if (BL3Node == null) {
	    				BL3Node = new ProgramBudget(j++, bl3);
	    				BL1Node.add(BL3Node);
						BudgetNode BL4Node = new BudgetLine(j++, bl4);
						BL3Node.add(BL4Node);    				
	    			}     			   			
	    		} else {
	    			System.debug('>>> New hierarchy');
					Budgets__c bl1 = new Budgets__c(Period__c = p.Id, 
													Budget_Area__c = budgetParent.Budget_Owner__r.Budget_Area__c, 
												    RecordTypeId = budgetParent.Budget_Owner__r.RecordTypeId,
												    Budget_Amount__c = 0);
	    			
	    			// If I am in a test then I create the name manually, just in case that the wf rule is inactive
	    			if (isTest) {
	    				bl1.Name = p.Name + ' ' + bl1.Budget_Area__c;
	    			}
	    				
	    			BudgetNode BL1Node = new Budgets(j++, bl1);
	    			recurringTree.add(BL1Node);
	    			
	    			BudgetNode BL3Node = new ProgramBudget(j++, bl3);
	    			BL1Node.add(BL3Node);
	    			
	    			BudgetNode BL4Node = new BudgetLine(j++, bl4);
	    			BL3Node.add(BL4Node);   			
	    		}
	    	}
	    	save(recurringTree); // save recurringTree
			}
		}
    }

    /*
     * Method: save()
     * Saves the tree to the database
     */    
    private static void save(BudgetNode tree) {
		errorMsg = BudgetUtil.save(tree);    
    }
}