src/objects/Budget_Line__c.object
<CustomObject>
    <description>Level 3 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Line_Amount__c</fullName>
        <label>Budget Line Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>Program_Budget__r.Budget_Owner__r.Period__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Budget_Amount__c</fullName>
        <formula>Program_Budget__r.Program_Budget_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Budget__c</fullName>
        <label>Program Budget</label>
        <referenceTo>Program_Budget__c</referenceTo>
        <relationshipLabel>Budget Lines (Level 3)</relationshipLabel>
        <relationshipName>Budget_Lines1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Budget Line</label>
    <nameField>
        <label>Budget Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budgets__c.object
<CustomObject>
    <description>Level 1 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Amount__c</fullName>
        <label>Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Area__c</fullName>
        <label>Budget Area</label>
        <picklist>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Projects</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget_Owner__c</fullName>
        <label>Budget Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Spend Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONTINGENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Spend Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Period__c.object
<CustomObject>
    <fields>
        <fullName>Number__c</fullName>
        <description>this number must be the  numeric year (2011, 2012, etc) or the numeric portion of the quarter (1,2,3,4 = Q1,Q2,Q3,Q4)</description>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentPeriod__c</fullName>
        <label>ParentPeriod</label>
        <referenceTo>Period__c</referenceTo>
        <relationshipLabel>Periods (ParentPeriod)</relationshipLabel>
        <relationshipName>Periods2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Budget__c.object
<CustomObject>
    <description>Level 2 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Area__c</fullName>
        <label>Budget Area</label>
        <picklist>
            <picklistValues>
                <fullName>Generica Area 1 (Update)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generica Area 2 (Update)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generica Area 3 (Update)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budget_Owner__c</fullName>
        <label>Parent Budget</label>
        <referenceTo>Budgets__c</referenceTo>
        <relationshipLabel>Program Budgets (Level 2)</relationshipLabel>
        <relationshipName>Program_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Budget_Amount__c</fullName>
        <label>Program Budget Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <picklist>
            <controllingField>Budget_Area__c</controllingField>
            <picklistValues>
                <fullName>Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Books/Brochures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branding/Awareness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Projects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Purchase_Request__c.object
<CustomObject>
    <description>Level 4 of the budgeting and planning hierarchy</description>
    <fields>
        <fullName>Budget_Line__c</fullName>
        <label>Budget Line</label>
        <referenceTo>Budget_Line__c</referenceTo>
        <relationshipLabel>Purchase Requests (Level 4)</relationshipLabel>
        <relationshipName>Purchase_Requests1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month_1_Amt__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>February
May
August
November</inlineHelpText>
        <label>Month 1 Amt (Feb, May, Aug, or Nov)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_2_Amt__c</fullName>
        <inlineHelpText>March
June
September
December</inlineHelpText>
        <label>Month 2 Amt (Mar, Jun, Sep, or Dec)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_3_Amt__c</fullName>
        <inlineHelpText>April
July
October
January</inlineHelpText>
        <label>Month 3 Amt (Apr, Jul, Oct or Jan)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Request_Amount__c</fullName>
        <label>Purchase Request Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>As a user you can choose: 
New/Not Submitted
Submitted
Change Request
Cancelled</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New/Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Request</label>
    <nameField>
        <label>Purchase Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BudgetChartTests.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

@isTest
private class BudgetChartTests {
	
	static testMethod void testBudgetsCharts(){
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test', Budget_Amount__c = Decimal.valueOf('1000'));
		insert budgets;
		System.assertNotEquals(null, budgets.Id);
		// insert program budgets
		Program_Budget__c pb1 = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test1', Program_Type__c = 'test1', Program_Budget_Amount__c = Decimal.valueOf('100'));
		Program_Budget__c pb2 = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test2', Program_Type__c = 'test2', Program_Budget_Amount__c = Decimal.valueOf('200'));
		Program_Budget__c pb3 = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test3', Program_Type__c = 'test3', Program_Budget_Amount__c = Decimal.valueOf('300'));
		insert new List<Program_Budget__c> {pb1,pb2,pb3};
		System.assertNotEquals(null, pb1.Id);
		System.assertNotEquals(null, pb2.Id);
		System.assertNotEquals(null, pb3.Id);
		
		System.assert(budgets.id != null);
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(budgets);
		BudgetOwnerChartController ctl = new BudgetOwnerChartController(stdCtl);
		System.assertEquals(ctl.budgetOwner.Id , budgets.Id);
		System.assertEquals(ctl.programBudgets.size(), 3);
		
		Decimal spendings = pb1.Program_Budget_Amount__c + pb2.Program_Budget_Amount__c + pb3.Program_Budget_Amount__c;
		System.assertEquals(ctl.spendings, spendings);
		System.assertEquals(ctl.savings, ctl.budgetOwner.Budget_Amount__c - spendings);
	}
	
	static testMethod void testBudgetChartAmountNull() {
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test');
		insert budgets;
		System.assertNotEquals(null, budgets.Id);

		System.assert(budgets.id != null);
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(budgets);
		BudgetOwnerChartController ctl = new BudgetOwnerChartController(stdCtl);
		System.assertEquals(ctl.budgetOwner.Id , budgets.Id);
		
		System.assertEquals(ctl.spendings, 0);
		System.assertEquals(ctl.savings, 0);	
	}
	
	static testMethod void testProgramBudgetChart(){
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test', Budget_Amount__c = Decimal.valueOf('1000'));
		insert budgets;
		System.assertNotEquals(null, budgets.Id);
		// insert program budgets
		Program_Budget__c pb = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test1', Program_Type__c = 'test1', Program_Budget_Amount__c = Decimal.valueOf('500'));
		insert pb;
		System.assertNotEquals(null, pb.Id);
		// insert budget lines
		Budget_Line__c bl1 = new Budget_Line__c(Program_Budget__c = pb.Id, Budget_Line_Amount__c = Decimal.valueOf('50'));
		Budget_Line__c bl2 = new Budget_Line__c(Program_Budget__c = pb.Id, Budget_Line_Amount__c = Decimal.valueOf('100'));
		Budget_Line__c bl3 = new Budget_Line__c(Program_Budget__c = pb.Id, Budget_Line_Amount__c = Decimal.valueOf('150'));
		insert new List<Budget_Line__c> {bl1,bl2,bl3};
		System.assertNotEquals(null, bl1.Id);
		System.assertNotEquals(null, bl2.Id);
		System.assertNotEquals(null, bl3.Id);
		
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(pb);
		ProgramBudgetChartController ctl = new ProgramBudgetChartController(stdCtl);
		System.assertEquals(ctl.programBudget.Id, pb.Id);
		Decimal spendings = bl1.Budget_Line_Amount__c + bl2.Budget_Line_Amount__c + bl3.Budget_Line_Amount__c;
		System.assertEquals(ctl.spendings, spendings);
		System.assertEquals(ctl.savings, ctl.programBudget.Program_Budget_Amount__c - spendings);
	}
	
	static testMethod void testProgramBudgetChartAmountNull() {
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test', Budget_Amount__c = Decimal.valueOf('1000'));
		insert budgets;
		System.assertNotEquals(null, budgets.Id);
		// insert program budgets
		Program_Budget__c pb = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test1', Program_Type__c = 'test1');
		insert pb;
		System.assertNotEquals(null, pb.Id);	

		ApexPages.StandardController stdCtl = new ApexPages.StandardController(pb);
		ProgramBudgetChartController ctl = new ProgramBudgetChartController(stdCtl);
		System.assertEquals(ctl.programBudget.Id, pb.Id);
		System.assertEquals(ctl.spendings, 0);
		System.assertEquals(ctl.savings, 0);
	}
	
	/*
	 * GUS ID: W-799610
	 * Pending Review: Guillermo Freire, Santiago Doval, Angelica Buffa
	 */
	static testMethod void testBudgetLineChart() {
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test', Budget_Amount__c = Decimal.valueOf('1000'));
		insert budgets;
		System.assertNotEquals(null, budgets.Id);
		// insert program budgets
		Program_Budget__c pb = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test1', Program_Type__c = 'test1', Program_Budget_Amount__c = Decimal.valueOf('500'));
		insert pb;
		System.assertNotEquals(null, pb.Id);
		// insert budget lines
		Budget_Line__c bl = new Budget_Line__c(Program_Budget__c = pb.Id, Budget_Line_Amount__c = Decimal.valueOf('400'));
		insert bl;
		System.assertNotEquals(null, bl.Id);
		
		// insert purchase requests
		Purchase_Request__c pr1 = new Purchase_Request__c(Budget_Line__c = bl.Id, Month_1_Amt__c = Decimal.valueOf('10'), Month_2_Amt__c = Decimal.valueOf('10'), Month_3_Amt__c = Decimal.valueOf('30'), Purchase_Request_Amount__c = Decimal.valueOf('50'), Status__c = 'New/Not Submitted');
		Purchase_Request__c pr2 = new Purchase_Request__c(Budget_Line__c = bl.Id, Month_1_Amt__c = Decimal.valueOf('10'), Month_2_Amt__c = Decimal.valueOf('10'), Month_3_Amt__c = Decimal.valueOf('40'), Purchase_Request_Amount__c = Decimal.valueOf('60'), Status__c = 'New/Not Submitted');
		Purchase_Request__c pr3 = new Purchase_Request__c(Budget_Line__c = bl.Id, Month_1_Amt__c = Decimal.valueOf('10'), Month_2_Amt__c = Decimal.valueOf('10'), Month_3_Amt__c = Decimal.valueOf('50'), Purchase_Request_Amount__c = Decimal.valueOf('70'), Status__c = 'New/Not Submitted');
		insert new List<Purchase_Request__c> {pr1,pr2,pr3};
		System.assertNotEquals(null, pr1.Id);
		System.assertNotEquals(null, pr2.Id);
		System.assertNotEquals(null, pr3.Id);
		
		ApexPages.StandardController stdCtl = new ApexPages.StandardController(bl);
		BudgetLineChartController ctl = new BudgetLineChartController(stdCtl);
		System.assertEquals(ctl.budgetLine.Id, bl.Id);
		System.assertEquals(ctl.purchaseRequests.size(), 3);
		// Check that the variables were loaded with the proper values
		Decimal spendings = pr1.Purchase_Request_Amount__c + pr2.Purchase_Request_Amount__c + pr3.Purchase_Request_Amount__c;
		System.assertEquals(ctl.spendings, spendings);
		System.assertEquals(ctl.savings, ctl.budgetLine.Budget_Line_Amount__c - spendings);
	}
	
	/*
	 * GUS ID: W-799610
	 * Pending Review: Guillermo Freire, Santiago Doval, Angelica Buffa
	 */	
	static testMethod void testBudgetLineCharAmountNull() {
		Period__c parentPeriod = new Period__c(Type__c = 'Year', Number__c = Decimal.valueOf('2050'));
		insert parentPeriod;
		System.assertNotEquals(null, parentPeriod.Id);
		Period__c p = new Period__c(parentPeriod__c = parentPeriod.Id, Type__c = 'Quarter', Number__c = Decimal.valueOf('4'));
		insert p;
		System.assertNotEquals(null, p.Id);
	
		// insert budget
		Budgets__c budgets = new Budgets__c(Period__c = p.Id, Name = 'Chart test', Budget_Amount__c = Decimal.valueOf('1000'));
		insert budgets;
		System.assertNotEquals(null, budgets.Id);
		// insert program budgets
		Program_Budget__c pb = new Program_Budget__c(Budget_Owner__c = budgets.Id, Budget_Area__c = 'test1', Program_Type__c = 'test1', Program_Budget_Amount__c = Decimal.valueOf('500'));
		insert pb;
		System.assertNotEquals(null, pb.Id);
		// insert budget lines
		Budget_Line__c bl = new Budget_Line__c(Program_Budget__c = pb.Id);
		insert bl;
		System.assertNotEquals(null, bl.Id);

		ApexPages.StandardController stdCtl = new ApexPages.StandardController(bl);
		BudgetLineChartController ctl = new BudgetLineChartController(stdCtl);
		System.assertEquals(ctl.budgetLine.Id, bl.Id);
		System.assertEquals(ctl.spendings, 0);
		System.assertEquals(ctl.savings, 0);		
	}
}